name: 'Commit message validator'
description: 'Enforce angular commit message convention with minimal dependancy only git and bash.'
author: 'Sébastien Boulle'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  commit_validator_no_jira:
    description: 'If set, no validation is done on JIRA refs.'
    required: false
  commit_validator_allow_temp:
    description: 'If set, no validation is done on `fixup!` and `squash!` commits.'
    required: false
runs:
  using: "composite"
  steps:
    - name: LS
      run: ls -al
      shell: bash

    - name: LS working
      working-directory: ${{ github.workspace }}
      run: ls -al
      shell: bash

    - name: Fetch base
      working-directory: ${{ github.workspace }}
      run: git fetch origin ${{ github.event.pull_request.base.sha }}
      shell: bash

    - name: Fetch head
      working-directory: ${{ github.workspace }}
      run: git fetch origin ${{ github.event.pull_request.base.sha }}
      shell: bash

    - name: Validation
      run: ${{ github.action_path }}/check.sh ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      shell: bash
